### ISSUE TITLE
UI: Include "CSV" as available format

### ISSUE THREAD

**Issue by yolile** [open-contracting/data-registry#111]
We should mention that the data can also be downloaded as CSV from the beginning and everywhere. Eg:

- In each result card at https://data-registry.datlab.eu/en/search/
- On each dataset page (eg https://data-registry.datlab.eu/en/collection/14) (including the header and the "Access data" section)

cc @duncandewhurst

**Comment by hrubyjan** [comment]
Available formats: JSON, Excel are meant to say this. In fact Excel should be CSV but maybe users accepts better the Excel version. Question for @sabahfromlondon

**Comment by yolile** [comment]
This is relevant for the cases where the users know that the dataset is big and Excel won't be able to open the file and therefore only CSV files are useful for them, so it would be nice to let them know that CSVs are available too.

**Comment by sabahfromlondon** [comment]
@yolile I'm happy to use both. Users I spoke to all said they "used Excel" and to my surprise never said referred to CSVs. I think all users will understand "Excel/CSV" so happy to update the wording. Thanks

**Comment by jpmckinney** [comment]
@sabahfromlondon How's this?

![Screen Shot 2021-08-27 at 8 39 06 PM](https://user-images.githubusercontent.com/26463/131200683-02d4d4c7-177f-4b7b-913d-f9eb23b923d3.png)

![Screen Shot 2021-08-27 at 8 41 00 PM](https://user-images.githubusercontent.com/26463/131200687-dc6e2acb-5187-440a-a52c-e2f07672bcf9.png)

![Screen Shot 2021-08-27 at 8 41 13 PM](https://user-images.githubusercontent.com/26463/131200690-46351cfa-eb92-42dc-98ca-bf96064b24ed.png)

There's also the boxes on the homepage, but I want to check with Georg, because I don't think users care about the Kingfisher database.

**Comment by sabahfromlondon** [comment]
Perfect, thanks! :)

**Comment by jpmckinney** [comment]
@yolile I think we can do this via translations? Or you can change the source strings if you prefer.

**Comment by yolile** [comment]
@jpmckinney yes, I will do it via translations, same as #142

**Comment by yolile** [comment]
This is done already, see for example https://github.com/open-contracting/data-registry/search?q=csv
