### ISSUE TITLE
Document heartbeat configuration and considerations

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#140]
The disabling of the heartbeat seems to go back to this commit in Pelican: https://github.com/open-contracting/pelican-backend/commit/17efc99f1d207225454fb38f580cec50cd07f899

However, as I wrote in the [Kingfisher Process technical specification](https://docs.google.com/document/d/1pED3ujU3SGMvBu9RYyM5atY6cEE_cmPt7XqgekE2jYs/edit):

> If a worker takes too long, [the heartbeat can timeout](https://github.com/pika/pika/#requesting-message-acknowledgements-from-another-thread) ([see more](https://pika.readthedocs.io/en/1.1.0/examples/heartbeat_and_blocked_timeouts.html)). Pelican disables the heartbeat, but this is [discouraged](https://stackoverflow.com/a/51755383/244258) by RabbitMQ developers. One solution is to use async consumers. Another solution is to do the work in a separate thread, for which I think the [threaded](https://github.com/pika/pika/blob/master/examples/basic_consumer_threaded.py) and [queued](https://github.com/pika/pika/blob/master/examples/consumer_queued.py) [examples](https://pika.readthedocs.io/en/stable/examples.html) are relevant. In any case, we should test whether our solution works, by setting a short heartbeat and having a worker sleep.

**Comment by jpmckinney** [comment]
It is disabled in Kingfisher Collect and pelican-frontend as well.

Kingfisher Process sets it to 5. pelican-backend was changed to set it to 100.

**Comment by jpmckinney** [comment]
Assigning for opinion for now.

**Comment by jpmckinney** [comment]
As discussed on call, @jakubkrafka will share some notes/links about his research and Datlab's experiences, so that we have a documented approach to when to set the heartbeat, and what to set it to.

**Comment by jakubkrafka** [comment]
From our experience heartbeat, and more specific rabbit connection itself can be a quite unstable independent of the settings. (There were many other, undocumented settings similar to heartbeat leading to closed connections etc. Maybe its better with never version of Rabbit - we use it for 5+ years and our views can be influenced by this)
Right now, all the consuming components (typically, the problem lies in long processing times, producers are fine) are implemented in the async mechanism (two threads, one doing the actual work, another one managing the connection). Additionally, for the long-running tasks, the messages are acknowledged when there is a point-of-no-return reached. I.e. import into dqv - once started, there is no easy revert possible (messages for next phase are already published for the yet unfinished job) the message is ack-ed before the mass import starts.
