### ISSUE TITLE
Consider adding a language filter

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/data-registry#198]
Resulting from [CRM-8032](https://crm.open-contracting.org/issues/8032).

One potential use-case is to find a group of publications based on the language of the publication. This can be useful for speakers of regional lingua-francas ie Latin America (Spanish), or ECA (Russian) and further east (Mandarin, Arabic) as well as users in the Anglosphere.

The registry already has filters, and lists the publication language (where available) on the publication page. It should be possible to filter by publication language.

**Comment by jpmckinney** [comment]
@sabahfromlondon What do you think?

**Comment by sabahfromlondon** [comment]
@jpmckinney sounds like an excellent idea. 

The use case in the ticket didn't come up in the user research, but I agree that we want to support users looking for examples of data in specific languages.

Do you want to use "Language" or "Publication language" as the label for the filter? I think I have a preference for "Publication language".

Can we manually add the language for the datasets where this is missing? For example:https://data.open-contracting.org/en/publication/12 - we can add the language as Czech?

**Comment by jpmckinney** [comment]
I'd go with "Publication language".

We will need to add a step for adding a new publication, to manually check the language in case it is not extractable from the data: https://github.com/open-contracting/data-registry/blob/main/.github/ISSUE_TEMPLATE/new-publication.md

We can also add a filter to the admin backend, to make it easy to find publications with blank languages. We need all publications to have a language set, otherwise a user can select a language and not have a relevant publication match.

**Comment by jpmckinney** [comment]
@yolile @sebasdocp  We have these languages (below).

That's a lot of languages to display on https://data.open-contracting.org/en/search/

We can use a dropdown, but visible options are better than hidden options.

As I understand, the use case is to discover *other* countries with the same language. So, for example, there are 4 Italian datasets, but they are all from Italy – so the language filter adds nothing compared to the country filter.

So, the rule can be that we include only languages that occur in multiple countries. With that, we'd get these languages (with number of countries):

```
 count | language_en 
-------+-------------
    16 | English
    15 | Spanish
     3 | French (France, Luxembourg, Canada)
     3 | German (Germany, Austria, Switzerland)
     2 | Dutch (Netherlands, Belgium)
     2 | Greek (Greece, Cyprus)
     2 | Albanian (Albania, Kosovo)
(7 rows)
```

What do you think the design should be? @yolile You can share additional info on use cases.

Full list if no filters applied (with number of datasets, instead of number of countries):

```
 count | language_en 
-------+-------------
    42 | Spanish
    36 | English
     5 | French
     4 | German
     4 | Italian
     3 | Dutch
     2 | Albanian
     2 | Croatian
     2 | Slovenian
     2 | Greek
     2 | Portuguese
     1 | Moldovan
     1 | Kyrgyz
     1 | Lithuanian
     1 | Romanian
     1 | Serbian
     1 | Danish
     1 | Macedonian
     1 | Bulgarian
     1 | Georgian
     1 | Estonian
     1 | Slovak
     1 | Hungarian
     1 | Czech
     1 | Icelandic
     1 | Polish
     1 | Latvian
     1 | Norwegian
     1 | Swedish
     1 | Indonesian
     1 | Finnish
(31 rows)
```

----

Queries:

```sql
SELECT COUNT(*), language_en FROM data_registry_collection GROUP BY language_en ORDER BY count DESC;
SELECT COUNT(DISTINCT(country_en)), language_en FROM data_registry_collection GROUP BY language_en HAVING COUNT(DISTINCT(country_en)) > 1 ORDER BY count DESC;
```

----

(Notes on how I set missing languages)

I filled in the OpenTender languages based on:

```fish
for i in 71 72 75 88 91 44 45 12 49 94 138 92 50 51 47 54 69 52 46 53 48 55 56 57 58 87 60 68 70 73 74 139 93 89 90
  echo $i
  curl -sS "https://data.open-contracting.org/en/publication/$i/download?name=2022.jsonl.gz" | gunzip - | head -n 3 | jq .buyer.name
end
```

If the two buyer names didn't look like they were the same language, I re-ran it with a sample of 10 and took the majority. For example:

* Belgium: 3/3 Dutch, but I checked 10 anyway and there was some French
* Cyprus: 1/10 English
* Czechia: 1/10 Slovak, not sure if misdetected
* EU Institutions: mostly English but also French, Romanian and some singletons out of 20
* Finland: 1/10 Swedish, not sure if misdetected
* Switzerland: mostly German but also French

Only unexpected was:

* Georgia: English (10/10)
* Ireland: English (2/10 Irish)
* Malta: English (10/10)

I'm not sure if the use case is just for the main language, or for all languages. In any case, for now, I changed the label on the detail page from "Language" to "Main language".

**Comment by yolile** [comment]
> @yolile You can share additional info on use cases.

To be honest, I haven't heard again from anyone about this need

**Comment by jpmckinney** [comment]
Aha, then I guess we can abandon the issue. FYI @sebasdocp 

FWIW, Spanish is LAC + Spain, which is very predictable and there is already a Region filter for LAC. English is Canada, UK, Australia, South Asia, Africa, and the unexpected ones mentioned (Georgia, Ireland, Malta).
