### ISSUE TITLE
Contact data support team needs to open in a new tab

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#260]
Contact data support team on the data details page needs to open in a new tab.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/11212467/201660367-9533a5ec-eca1-4b2a-bc8b-f610d568b3ae.png">

**Comment by jpmckinney** [comment]
It's a mailto: link, so behavior depends on user setup (mine opens a window in my email client). What does it do for you?

**Comment by jpmckinney** [comment]
I'll change it to open in a new tab (in Safari at least, mailto: won't create a new empty tab if the mailto: protocol is linked to an external program).

The feedback modal got removed while removing Vue, which was causing bugs that were severe (e.g. irremovable filters). We can add it back, but it is so far down the list as a rarely used feature – I'm not sure it'll happen.

We can put the email address directly on the page (data@open-contracting.org) so that people whose mailto: isn't configured to their preferred email can send the email as they like.

**Comment by jpmckinney** [comment]
I made the commit to open in a new tab. It hasn't been deployed yet. We can create a new issue about the feedback form, but it is very likely to remain open indefinitely.
