### ISSUE TITLE
Only provide links to free decompression tools

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#262]
WinZip and WinRAR are not free (they only have free trials), so we should only recommend free options. 

7-Zip is free to we should keep that option. Other options can be found here: https://rigorousthemes.com/blog/best-free-winzip-alternatives/

Also links to these tools need to open in a new tab. Currently they don't.

**Comment by jpmckinney** [comment]
7-zip is listed first because it's the free option. WinZip and WinRAR are listed because they are the most common tools for this purpose, and the free trials work fine (they are shareware). Many Windows users have WinZip and WinRAR, so their listing implies "Aha, I can use the tool I already have". We don't want, "Gosh, I need to install this 7-Zip thing now?".

**Comment by jpmckinney** [comment]
The other software listed has very low market share. I wouldn't feel comfortable recommending a tool I haven't used. The only one listed besides 7-Zip that is popular is The Unarchiver for macOS - but macOS can open all our files on its own without external software.

**Comment by jpmckinney** [comment]
I've made the commit to open in new tabs. It hasn't been deployed yet.

**Comment by jpmckinney** [comment]
Agreed on call to leave software options as-is. Now deployed.

Example: https://data.open-contracting.org/en/publication/17
