### ISSUE TITLE
Update text in boxes on homepage

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#269]
Please update the text in the boxes for "Learn about the source" and "Get directed". Text pasted below for ease.

**Learn about the source**
Each source comes with information to help you understand what fields are part of the datasets and if it includes documents. 
We have also included information on any known data quality issues and advice on how to access the data.

Edit: Final text for last sentence:

> We include information on any known data quality issues.

**Get directed**
Through the Data Registry, whole OCDS datasets are available to download in bulk. 
Data can be downloaded in JSON, Excel or CSV.

Edit: Final text:

>  Whole OCDS datasets are available to download in bulk, in JSON, Excel and CSV formats.

<img width="1440" alt="Desktop HD V2 Home Design" src="https://user-images.githubusercontent.com/11212467/204322270-1d7d37db-3d4f-4672-bca9-26697fd06f58.png">

**Comment by jpmckinney** [comment]
> We have also included information on any known data quality issues and advice on how to access the data.

Rather than changing the past tense to the past perfect tense, I think it reads better to use the present tense:

We include information on any known data quality issues and advice on how to access the data

> Get directed

This heading doesn't make sense to me. The current heading is "Get direct access to the source data", which is clear.

> Through the Data Registry, whole OCDS datasets are available to download in bulk. Data can be downloaded in JSON, Excel or CSV.

"Through the Data Registry" is obvious. I'd go with:

Whole OCDS datasets are available to download in bulk, in JSON, Excel and CSV formats.

**Comment by yolile** [comment]
From https://github.com/open-contracting/data-registry/issues/246#issue-1383141958:

> In the " Learn about the source" box, it says, "We also included any known data quality issues and advice on how to access the data."
> 
> I think we are not providing advice on how to access the data.
> 
> In " Get direct access to the source data": "You can also customize the data fields you need for a more manageable dataset."
> That is not true at the moment.

**Comment by jpmckinney** [comment]
I agree that "advice on how to access the data" is not quite right/clear. Anyhow, that part is covered in the last box, so we can maybe just delete it.

**Comment by duncandewhurst** [comment]
FYI that the registry home page still says 'You can also customize the data fields you need for a more manageable dataset', but as far as I can see that functionality isn't actually available.

**Comment by jpmckinney** [comment]
> Get direct access to the source data

The whole purpose of the registry is providing *indirect* access to the source data (because direct access involves slow servers etc.), so I've changed to "Get instant access to data"

> Original: Information about each data source is provided to help you to understand what fields are available or if there are any documents.

> Proposed: Each source comes with information to help you understand what fields are part of the datasets and if it includes documents.

> Meta description (for context): Learn about the data source's coverage, features and quality issues.

The proposed text is a bit clumsy (sources don't "come with information"), there's a grammatical issue viz number agreement (source -> dataset**s**), and the use of dataset vs source is confusing. I'll go with:

> For each dataset, we describe its source and coverage, at both an administrative level (public bodies, systems and procedures covered) and technical level (fields covered and linked documents).
