### ISSUE TITLE
Feedback email

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#64]
Please give me an email of a recipient of the user's feedback
What should be the email content? - subject, body

We have `Type of feedback` and the feedback itself. We should also identify the source. Should we send any other additional information?

**Comment by jpmckinney** [comment]
Let's do jmckinney@open-contracting.org for now.

**Comment by sabahfromlondon** [comment]
@hrubyjan just to clarify, are you referring to the copy for this:

<img width="580" alt="Screenshot 2021-06-22 114433" src="https://user-images.githubusercontent.com/11212467/122911477-40ebbb80-d34f-11eb-9305-59ab00bb1163.png">

**Comment by hrubyjan** [comment]
yes, @sabahfromlondon we need to define the `Submit feedback` action. It will be an email and the question is what will be the content

**Comment by sabahfromlondon** [comment]
Thanks for the clarification. 

Here is the content for the feedback email to send to users. I have tried to keep the content generic, so we can have one automated email for all of the issues types. @jpmckinney do you want to check you're happy with this content since I've put your name at the bottom on the email?

**Email title:**
Thank you for your feedback on the [dataset country and title] dataset.

**Email Heading (H1)**
Thank you for your feedback. 

**Email body content**
Here's what you told us:

[type of feedback dropdown option selected]
[content of feedback in text field]

Thank you for taking the time to provide feedback on the [dataset country and title] dataset. We work hard to maintain and improve the open contracting data registry and to support data publishers with improving the quality of the data they provide. Feedback from users of data and the open data community is a hugely valuable part of that process.

We have noted the issue(s) and will either try to resolve the problem or will provide other data registry users with further advice for this dataset.

We hope to see you again soon!

James McKinney
Head of Data Products and Services

**Comment by sabahfromlondon** [comment]
@hrubyjan can we also update the text in the feedback submission popup? Here's the text:

We welcome all feedback from the users of the data registry and from the open data community. To provide your feedback, please complete the form below.

**Comment by jpmckinney** [comment]
Looks good!

@hrubyjan We use a noreply@noreply.open-contracting.org address. I can send the SMTP credentials whenever.

**Comment by sabahfromlondon** [comment]
Thanks @jpmckinney.

@hrubyjan please share the design for the email for us to take a look at :)

**Comment by hrubyjan** [comment]
A little misunderstanding. I thought we will only send an email to OCP helpdesk (simple text no complicated designs). I was just wondering what should be the content and what are the important information to share with helpdesk.

Do you think we should also send an email to the user? From my perspective it's email sentenced to immediate deletion but maybe users want to be assured that you got the feedback. It just looks like non-essential work now.

**Comment by jpmckinney** [comment]
I consider an email to the user to be nice-to-have - a confirmation message on the web should be sufficient.

**Comment by sabahfromlondon** [comment]
Woops my bad. Sorry about that. I guess we have the content in case we change our mind in the future.

For the helpdesk receiving the email, this is quite straightforward.

**Email title:**
You have new feedback on the [dataset country and title] dataset.

**Email body content**
The following feedback was provided for the [dataset country and title] dataset.

Type of feedback: [type of feedback dropdown option selected]
Feedback detail: [content of feedback in text field]

The feedback should be followed up with in the data registry by either fixing the issues e.g. a broken link, or by proving further advice and guidance to users.

**Comment by hrubyjan** [comment]
I created new issue #98 based on this discussion
