### ISSUE TITLE
Search result

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/data-registry#8]
Here are several options how to design a result list item. Those differs in
- how to display the flag. 
  - I like the big flag over the whole height of the item but I'm aware of the fact that not all the flags can easily fit into this format and this needs some additional work to properly say how each flag should be displayed
  - on the other hand this is here for quick orientation not to display each flag perfectly
- how to display the data standard (OCDS, Digiwhist, Custom)
  - for the first version it's unnecessary as it's always OCDS, maybe we don't need the information here but if we remove all unnecessary information then we also remove data formats (JSON, Excel), Accessed from and the item will be very minimalistic which I don't like
- How to display (non)available formats

I like the most combination of the first and the second option. `Access from` from the first and `OCDS` label  from the second. `Available formats` are same in both versions

What are your prefferences?
![image](https://user-images.githubusercontent.com/17906453/108852808-555cb900-75e6-11eb-9490-0729c2c8c554.png)

Title which is now `Datasets by country` on the top
![image](https://user-images.githubusercontent.com/17906453/108854265-f7c96c00-75e7-11eb-9d91-47cdff5825e7.png)

**Comment by jpmckinney** [comment]
I'll wait for Sabah's comments, but for the question of what data to include in each result card: If the data is the same for all results, it should be omitted, since it isn't informative. If we later add new sources besides Kingfisher Collect or standards besides OCDS, then we can revise the design.

**Comment by sabahfromlondon** [comment]
Yes the OCDS Kingfisher bit can go. I wasn't sure about keeping it in or removing it. If we're fine with having to change the design later then I agree for now it provides no value.

**Comment by sabahfromlondon** [comment]
**On flag design**
- I actually think I prefer the smaller flag because it is consistent with how the flag is represented in the Data Details page. 
- I also don't want to run into issues with future flags not being clear to users.

**Comment by sabahfromlondon** [comment]
I think I mentioned before but will just put it here in writing. The non-available data just needs the be displayed without the crossing out.

**Comment by hrubyjan** [comment]
There are actually 4 pieces of information that are always the same
- Access from: Kingfisher
- Data standard: OCDS (we only proces OCDS data from kingfisher)
- Available formats (both will be always available as dumps and via flatten tool)
  - JSON
  - Excel

We should somewhere communicate this to the user. We can either keep the same values on all cards or we can communicate it some other way but user should now that we provide OCDS data in it's original JSON format or flattened to Excel files.

This information is provided on a landing page bud it is stressed enough?

**Comment by sabahfromlondon** [comment]
The reason for having this information is feedback, confirmation and assurance for what the user will be getting. 

Originally, having the Kingfisher reference was to help users understand that they are getting data from the OCP, rather than just being direction to an external source. This was before we decided that for the MVP we would focus on data in Kingfisher only. 

The feedback from users was that this was reassuring. I think we can remove this reference in the search page, as this feedback can be effectively provided on the homepage (with some tweaks to the current content).

**Comment by hrubyjan** [comment]
@sabahfromlondon search result updated

![image](https://user-images.githubusercontent.com/17906453/109950292-a6526880-7cdc-11eb-9fcb-c1c1fa3f75ae.png)

**Comment by hrubyjan** [comment]
@sabahfromlondon I have two more questions
1) Data date range on the search result item - not sure whether this should display date range of releases of the whole dataset or should be in a harmony with the filter value
2) Dates format for `Data date range` and `Last updated` - full date (what format then?) o only MMM YYYY. If only MMM YYYY then the correct value for Data date range  from 2020-03-31  to 2020-04-01 is Mar 2020 to Apr 2020?

**Comment by sabahfromlondon** [comment]
@hrubyjan - thanks for the questions. 

1. The result should be the date range of the releases of the whole dataset, that is within the date range selected by the user
2. For the best user experience, I'm thinking the custom date range option needs to be option to select month and year only. Whether the date of a release is the 15th or the 16th of March is not going to make a difference to the user. Feedback for dates in the form of MMM YYYY is much nicer.

**Comment by jpmckinney** [comment]
For (2), I agree: I think cases like 2020-03-31 to 2020-04-01 (2 days of data) will be quite rare, so I agree it's simpler for the user if the UI just states Mar 2020 to Apr 2020 (which implies 2 months of data).

For (1), I think it's a bit odd if the search result items show different date ranges whenever the user changes the data range selected. Isn't it less confusing to the user if the range is always the same, regardless of the filter's value? Any results that don't match the range will be filtered out anyway; if the result's range must match the filter's range, it will just be identical for all results, which is not informative.

**Comment by sabahfromlondon** [comment]
for (1) I don't think it's confusing for the range to match the filter value, it's the opposite. I think if we showed the full range here the user will think that they have to download data for the whole range. 

I agree that that if the results don't match then the range will be filtered out, but if there is a partial match then we need to show for what part of the query we have data.

**Comment by jpmckinney** [comment]
How does the logic for a partial match work? I would have thought it only returns full matches.

I think it'd be clearer to just omit the range on individual results when the date filter is used. Otherwise, as I understand, the same information will just be repeated.

I do think it's odd for the same data element to display different information depending on the state of filters. I don't know any search interface that does that...

**Comment by sabahfromlondon** [comment]
Here is what I think should happen:

- If a user enters the date range April 2015 to March 2016 for a source and we have data for that whole date range then the result presented is April 2015 to March 2016
- If a user enters the date range April 2015 to March 2016 for a source and we only have data for January 2016 to present day, then the result presented is January 2016 to March 2016.
- If a user enters the date range April 2015 to March 2016 for a source and we don't have any date for that time range or for that source then we do not return a result.

The point of adding the date range is to provide feedback to the user that we have what they are looking for or have part of what they are looking for. Not returning a result, for a partial match is a little too unhelpful imho.

Regarding this point => _I do think it's odd for the same data element to display different information depending on the state of filters. I don't know any search interface that does that..._

If I'm booking a hotel room and I enter the dates for when I would like to book a room for, then I only want results for those dates. No interface returns a result to say here are the rooms we have and here are all the possible dates across years for which this room is available. Many interfaces to however, suggest that if you adjust your dates slightly then you can get a room that is not available for the exact date range specified (usually this works to help people find something within their price range). 

If we go back to the user that enters the date range April 2015 to March 2016 for a source. If we only have data for January 2016 to present day, then the user might think "ok how about I search for April 2016 to March 2017 instead". Some users will want data for that exact date range (not much the registry can do about that), others will be more compromising and try to work with what is available. Indicating that there is something available therefore becomes important. This is why I am keen on showing a partial match.

**Comment by jpmckinney** [comment]
Aha, yes, partial matches make sense, thanks for explaining.

I'm concerned that using the same label with two different meanings is still an issue. "Data date range" (maybe rename to "date range available") at first means "earliest and last dates for which this dataset has data". Then, adding a filter changes the meaning to that plus "within the date range you specified". In a hotel booking there's no such issue, because if you haven't selected dates, the results don't contain any date information (like when exploring stays on Airbnb). 

Some ways to address this are:

1. Change the label from "Date range available" to "Data range matched". However, this might be an unexpected and therefore unnoticed change for the user, since it's in the same location as the earlier element.

1. Add a separate element under the first range like below. However, this makes the result even taller.

    > Date range matched: March 2015 – April 2016

1. Change the value to present the window the user is interested in, in the context of the wider range like below. However, it might not be obvious how to interpret this (though there might be better designs).

    > Date range available: Sep 2009 … **March 2015 – April 2016** … Aug 2020

1. Have some visual representation of how the desired window overlaps with the available range. The trouble with this is that different datasets have different range sizes, so it's probably not possible to scale correctly.

Anyway, maybe this is too much work for one data element, and we just leave it as-is.

**Comment by sabahfromlondon** [comment]
Thanks James. I like option 1 and agree with you on the label names. We could try having the two labels in different locations. That should help users to notice that something has changed when they apply a filter.

**Comment by hrubyjan** [comment]
My opinion here is that the search result item for a particular dataset should remain basically static no matter how filter options are set. 

So in my eyes the search result item should contain information about the whole dataset `Data available for: Feb 2013 - Dec 2020` even if the `Data date range` is set to `Jan 2019 - Dec 2019`. 

I'm pretty sure that the user will not spot that we, for example, added one label or will not understand some hidden meanings. 
I also think that in many cases user will completely omit the date filter. In such case E.g. 
option 1 - consider that the user will ignore the filter and keep the value `All`.  I guess `Data range matched` can be confusing. Matched with what?
option 2 - both values will be the same?

The only thing I would add is something like red exclamation mark icon before  `Data available for` label with a tooltip that `the dataset does not contain data for the whole requested period` so that it catches user's attention when browsing the results.

**Comment by sabahfromlondon** [comment]
@hrubyjan 

- For option 1, what James was saying was **IF** the filter is used. 
- I don't think option 2 is viable. 

Tool tips are terrible UX. The most basic advice is to avoid them whenever possible.

**Comment by jpmckinney** [comment]
Regarding whether to include the matched range at all, @sabahfromlondon had written:

> I think if we showed the full range here the user will think that they have to download data for the whole range.

However, I'm not sure that they will think that. We can maybe test it.

I agree with @hrubyjan that result entries being the same, regardless of filters, is a common pattern. The user has a mental model that the filters change which results appear in the results panel; they don't typically have a mental model that the filters change the information within each result.

However, there are examples of interfaces in which some parts of the result is highlighted, whether to warn (like @hrubyjan's suggestion) or otherwise draw attention (like "3 tickets left", etc.). It doesn't have to be a tooltip - it can be text directly in the result that is styled so as to draw attention.

**Comment by sabahfromlondon** [comment]
@james I agree we can speculate all we like, but will only know for sure when we test and ideally in a natural setting, rather than me hovering over participants in a study.

Additional text is probably our best option, which is why I suggested having two labels in different locations. 

Agree we can do more and draw attention and highlight the result for 'Date range matched'

**Comment by hrubyjan** [comment]
Here are some proposals let me know what you think. Of course we can combine different proposals or come with some new ones. Although I would not spend too much time on this :)
![image](https://user-images.githubusercontent.com/17906453/111653977-9d978180-8808-11eb-8b7e-c296afa20fd3.png)

**Comment by sabahfromlondon** [comment]
@hrubyjan thanks for providing the options. Can we go with the third one please? I think it will be the best way to get the user attention.

**Comment by hrubyjan** [comment]
👍  I also prefer this option
