### ISSUE TITLE
Pagination on Datasets by country

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/data-registry#85]
I had pagination on the UX design for this page. 

Perhaps not an ultimate must have right now since we only have 35 datasets, but this is good practice for the interface and will be more important as we add more sources.

**Comment by jpmckinney** [comment]
I'm not sure that in this case pagination is a good pattern. https://www.nngroup.com/articles/item-list-view-all/

The case for pagination is:

* "a user’s goal is not to peruse the full list"
* "you can prioritize the list items" (so that "users are likely to find what they want close to the top")
* there are more than "100 items" to display ("though it can be more or less depending on how easy it is for users to scan items and how much a long page impacts the response time")

In our case, we don't prioritize the list items. We only change the length of the list via filters.

Also, a user's goal might very well be to see the whole list to get a sense of the full corpus of OCDS data.

We currently are around the proposed maximum of 100.

I think we can do without pagination for the foreseeable future.

**Comment by sabahfromlondon** [comment]
Ok we can leave it. 

For anyone that might re-visit this ticket in the future what I had in mind was to have a defualt of 10 results. Your link for NNG does suggest this: "It’s usually better to offer a single default number — such as 10 or 20 — and supplement it with View All for people who want more."

The reason I thought pagination would be good was so that users would not have to scroll all the way to the top to view the filters. However, we can resolve that by other means in future with either a sticky faceted search or a back to top button if we want.
