### ISSUE TITLE
Probably too strict firewall settings for amy01

### ISSUE THREAD

**Issue by jakubkrafka** [open-contracting/data-registry#89]
The firewall settings on amy01 has been (probably) altered to disable all outgoing traffic. However, such settings will block deployment, data scraping itself etc. 

```
wget https://www.open-contracting.org                                    
--2021-07-14 13:23:59--  https://www.open-contracting.org/
Resolving www.open-contracting.org (www.open-contracting.org)... 178.79.188.127
Connecting to www.open-contracting.org (www.open-contracting.org)|178.79.188.127|:443... failed: Connection timed out.
Retrying.
```

**Comment by jpmckinney** [comment]
@RobHooper Can you allow all outgoing traffic?

**Comment by RobHooper** [comment]
@jakubkrafka @jpmckinney , the firewall is indeed the problem, it isn't blocking outbound traffic but because the firewall doesn't keep track of connections (stateless), it doesn't identify the request is a response and blocks it.

I've allowed TCP ack connections on Ephemeral Ports and I can confirm this fixes it by running the wget.

**Comment by RobHooper** [comment]
@jakubkrafka @jpmckinney , just checking we're happy with the firewall after the above changes and that this issue is fixed?
If we're I'll write up documentation on using the Hetzner firewall.
