### ISSUE TITLE
Automate deletion of older data

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#93]
We only need to keep the two most recent versions (so that we can fallback to the last version if we discover an issue with the current version).

**Comment by hrubyjan** [comment]
- We want to implement one script in the data registry that can erase data for the whole job. 
- Then we'd like to also implement a logic that erase all jobs except 
  - last two for each collection so that we don't have to do it one by one
  - active jobs (`data_registry_job.active = true`)

Job context in data registry

```
{
    "job_id": "3c18f2ecd98211eb9748a8a159689b50",
    "spider": "digiwhist_luxembourg",
    "pelican_id": 1053,
    "process_id": "322",
    "scrapy_log": "http://localhost:6800/logs/kingfisher/digiwhist_luxembourg/3c18f2ecd98211eb9748a8a159689b50.log",
    "process_id_pelican": 323,
    "pelican_dataset_name": "digiwhist_luxembourg_2021-06-30T09:04:57_136",
    "process_data_version": "2021-06-30T09:04:57"
}
```

## Data registry
- delete from data_registry_task where job_id = ?
- delete from data_registry_job where id = ?

## Pelican
use `pelican_id` from job context to delete all data in pelican

- delete from production.resource_level_check where dataset_id = ?;
- delete from production.field_level_check where dataset_id = ?;
- delete from production.progress_monitor_item where dataset_id = ?;
- delete from production.data_item where dataset_id = ?;
- delete from production.progress_monitor_dataset where dataset_id = ?;
- delete from production.dataset where id = ?;

## Process
we already have `wipe_collection.sh` script. Not sure whether the input id is a compiled collection in this case weshould use `process_id_pelican` from job context. If the input is the original collection then we should use `process_id` from the job context

## Collect
I don't know how collected data are being stored, but you know it @jakubkrafka :), so please delete it too
use `pelican_id` from job context to delete all data in pelican

**Comment by jpmckinney** [comment]
For Process, where is this wipe_collection.sh file? Why isn't it part of Process' CLI?

For Collect, it's stored in: `FILES_STORE` directory (set by environment variable) / spider_name / YYYYMMDD_HHMMSS

**Comment by jakubkrafka** [comment]
> For Process, where is this wipe_collection.sh file? Why isn't it part of Process' CLI?
@jpmckinney - Its of course part of the Process CLI (as a command and API endpoint as well), no need to worry here:) 
wipe_collection.sh is only a simple wrapper to run that command from the docker container (@hrubyjan didnt know that:))

**Comment by jakubkrafka** [comment]
Prepared following steps:

### Data registry
shoud it be really deleted? not marked in a special state?

### pelican-frontend
new api endpoint dataset_wipe (equivalent of currently used dataset_start)

### pelican-backend
new worker to delete collection - wiper

### kingfisher-process
api endpoint to wipe_collection (equivalent of currently used create_collection)

### exporter
new rabbit worker to delete generated exports
new api endpoint wiper_start (equivalent of currently used export_start) 

### kingfisher-collect
problematic part as there is no real API:( (dirty direct "involvement" from outside needed)
added new config param to data-registry SCRAPY_FILES_STORE (equivalent of FILES_STORE in srapy)
should be deleted by shutils.rmtree directly

All the steps above are very easy (update of existing API calls) to implement in some "logic" once the "logic" will be analysed and prepared.
